from __future__ import annotations

import os
import sys

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

import numpy as np
import pandas as pd   # ✅ 必须有

from shared import build_feature_set

DEFAULT_ALIASES = {
    "account_id": [
        "account_id", "customer_id", "consumer_id", "client_id", "acct_id",
        "account", "customerid", "consumerid"
    ],
    "subscription_id": ["subscription_id", "sub_id", "subscription", "contract_id", "plan_id"],
    "signup_date": ["signup_date", "created_at", "account_created", "account_creation_date", "start_signup_date"],
    "as_of_date": ["as_of_date", "asof_date", "snapshot_date", "scoring_date", "run_date", "date"],
    "start_date": ["start_date", "contract_start", "subscription_start", "sub_start_date"],
    "end_date": ["end_date", "contract_end", "subscription_end", "sub_end_date"],
    "usage_date": ["usage_date", "event_date", "timestamp"],
    "submitted_at": ["submitted_at", "ticket_created_at", "opened_at"],
    "usage_count": ["usage_count", "events", "event_count", "usage_events"],
    "ticket_id": ["ticket_id", "case_id", "support_id", "id"],
    "satisfaction_score": ["satisfaction_score", "csat", "csat_score", "satisfaction", "nps_score"],
    "plan_tier": ["plan_tier", "tier", "plan", "plan_name"],
    "seats": ["seats", "licensed_seats", "licenses", "seat_count"],
    "arr_amount": ["arr_amount", "arr", "mrr", "mrr_amount", "revenue"],
}


def _normalize_cols(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df.columns = [str(c).strip() for c in df.columns]
    return df


def _apply_aliases(df: pd.DataFrame, aliases: dict) -> pd.DataFrame:
    df = _normalize_cols(df)
    cols_lower = {c.lower(): c for c in df.columns}
    for canonical, alts in aliases.items():
        if canonical in df.columns:
            continue
        found = None
        for a in alts:
            if a.lower() in cols_lower:
                found = cols_lower[a.lower()]
                break
        if found is not None:
            df = df.rename(columns={found: canonical})
    return df


def _safe_datetime(s):
    return pd.to_datetime(s, errors="coerce")


def _zscore(series: pd.Series) -> pd.Series:
    x = pd.to_numeric(series, errors="coerce").astype(float)
    mu = np.nanmean(x)
    sd = np.nanstd(x)
    if not np.isfinite(sd) or sd <= 1e-12:
        return pd.Series(np.zeros(len(x)), index=series.index)
    return (x - mu) / sd


def build_from_single_raw_current_prev(df: pd.DataFrame) -> pd.DataFrame:
    """
    Input: a single wide file containing "current" and "prev" quarter values per account.
    Output: meta columns + the 16 model FEATURES generated by shared.build_feature_set().
    """
    df = _apply_aliases(df, DEFAULT_ALIASES)
    df = _normalize_cols(df).copy()

    required = [
        "account_id",
        "plan_tier",
        "usage_count_current",
        "usage_count_prev",
        "tickets_opened_current",
        "tickets_opened_prev",
        "days_to_contract_end_current",
    ]
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(f"Single RAW CSV missing required columns: {missing}")

    # -------------------------
    # dates
    # -------------------------
    if "as_of_date" not in df.columns:
        df["as_of_date"] = pd.Timestamp.today().normalize()
        df["as_of_date_inferred_flag"] = 1
    else:
        df["as_of_date_inferred_flag"] = 0
    df["as_of_date"] = _safe_datetime(df["as_of_date"])

    if "signup_date" not in df.columns:
        # default: 180 days before as_of_date
        df["signup_date"] = df["as_of_date"] - pd.to_timedelta(180, unit="D")
        df["signup_date_inferred_flag"] = 1
    else:
        df["signup_date_inferred_flag"] = 0
    df["signup_date"] = _safe_datetime(df["signup_date"])

    df["quarter_end"] = df["as_of_date"].dt.to_period("Q").dt.to_timestamp(how="end")

    # -------------------------
    # QoQ deltas / flags
    # -------------------------
    u_cur = pd.to_numeric(df["usage_count_current"], errors="coerce").fillna(0)
    u_prev = pd.to_numeric(df["usage_count_prev"], errors="coerce").fillna(0)
    t_cur = pd.to_numeric(df["tickets_opened_current"], errors="coerce").fillna(0)
    t_prev = pd.to_numeric(df["tickets_opened_prev"], errors="coerce").fillna(0)

    df["usage_count_qoq_delta_z"] = _zscore(u_cur - u_prev)
    df["tickets_opened_qoq_delta_z"] = _zscore(t_cur - t_prev)
    df["usage_drop_flag"] = ((u_cur - u_prev) < 0).astype(int)

    # seats (optional)
    if "seats_current" in df.columns:
        s_cur = pd.to_numeric(df["seats_current"], errors="coerce").fillna(0)
        if "seats_prev" in df.columns:
            s_prev = pd.to_numeric(df["seats_prev"], errors="coerce").fillna(0)
        else:
            s_prev = s_cur
        df["seats"] = s_cur
        df["seats_qoq_delta_z"] = _zscore(s_cur - s_prev)
    else:
        df["seats"] = 0.0
        df["seats_qoq_delta_z"] = 0.0

    # ARR (optional)
    if "arr_current" in df.columns:
        a_cur = pd.to_numeric(df["arr_current"], errors="coerce").fillna(0)
        if "arr_prev" in df.columns:
            a_prev = pd.to_numeric(df["arr_prev"], errors="coerce").fillna(0)
        else:
            a_prev = a_cur
        df["arr_amount_qoq_delta_z"] = _zscore(a_cur - a_prev)
    else:
        df["arr_amount_qoq_delta_z"] = 0.0

    # contract days
    df["days_to_contract_end_asof_qend"] = pd.to_numeric(df["days_to_contract_end_current"], errors="coerce")
    df["contract_missing_flag"] = df["days_to_contract_end_asof_qend"].isna().astype(int)
    df["days_to_contract_end_asof_qend"] = df["days_to_contract_end_asof_qend"].fillna(365)

    # satisfaction (optional)
    if "avg_satisfaction_current" in df.columns:
        df["avg_satisfaction"] = pd.to_numeric(df["avg_satisfaction_current"], errors="coerce")
    else:
        df["avg_satisfaction"] = np.nan
    df["satisfaction_missing_flag"] = df["avg_satisfaction"].isna().astype(int)

    # make sure plan_tier is string
    df["plan_tier"] = df["plan_tier"].astype(str)

    # ------------------------------------------------------------
    # Single source of truth: build final 16 model features here
    # ------------------------------------------------------------
    features_only = build_feature_set(df)

    # Meta columns for UI/debugging (do NOT duplicate plan_tier)
    meta = df[
        [
            "account_id",
            "signup_date",
            "as_of_date",
            "quarter_end",
            "signup_date_inferred_flag",
            "as_of_date_inferred_flag",
        ]
    ].copy()
    meta["account_id"] = meta["account_id"].astype(str)

    out = pd.concat([meta.reset_index(drop=True), features_only.reset_index(drop=True)], axis=1)
    return out


def build_from_raw_multi(
    accounts: pd.DataFrame,
    subscriptions: pd.DataFrame,
    usage: pd.DataFrame | None = None,
    tickets: pd.DataFrame | None = None,
) -> pd.DataFrame:
    """
    Multi-file mode:
      - accounts.csv: account_id, signup_date (optional)
      - subscriptions.csv: subscription_id, account_id, start_date, end_date, plan_tier, (optional seats, arr_amount)
      - usage.csv (optional): subscription_id, usage_date, usage_count (optional; default 1 per row)
      - tickets.csv (optional): account_id, submitted_at, satisfaction_score (optional)

    Output is the same as build_from_single_raw_current_prev(): meta + 16 FEATURES.
    """
    accounts = _apply_aliases(accounts, DEFAULT_ALIASES)
    subscriptions = _apply_aliases(subscriptions, DEFAULT_ALIASES)

    if "account_id" not in accounts.columns:
        raise ValueError("accounts.csv missing required column: account_id")
    if "signup_date" not in accounts.columns:
        accounts["signup_date"] = pd.NaT
    accounts["signup_date"] = _safe_datetime(accounts["signup_date"])

    req_sub = ["subscription_id", "account_id", "start_date", "end_date", "plan_tier"]
    missing_sub = [c for c in req_sub if c not in subscriptions.columns]
    if missing_sub:
        raise ValueError(f"subscriptions.csv missing required columns: {missing_sub}")

    subscriptions["start_date"] = _safe_datetime(subscriptions["start_date"])
    subscriptions["end_date"] = _safe_datetime(subscriptions["end_date"])

    # -------------------------
    # determine anchor date
    # -------------------------
    candidates = []

    if usage is not None:
        usage = _apply_aliases(usage, DEFAULT_ALIASES)
        if "usage_date" in usage.columns:
            usage["usage_date"] = _safe_datetime(usage["usage_date"])
            if usage["usage_date"].notna().any():
                candidates.append(usage["usage_date"].max())

    if tickets is not None:
        tickets = _apply_aliases(tickets, DEFAULT_ALIASES)
        if "submitted_at" in tickets.columns:
            tickets["submitted_at"] = _safe_datetime(tickets["submitted_at"])
            if tickets["submitted_at"].notna().any():
                candidates.append(tickets["submitted_at"].max())

    if subscriptions["start_date"].notna().any():
        candidates.append(subscriptions["start_date"].max())
    if subscriptions["end_date"].notna().any():
        candidates.append(min(subscriptions["end_date"].max(), pd.Timestamp.today()))

    if len(candidates) == 0 or pd.isna(max(candidates)):
        anchor = pd.Timestamp.today()
    else:
        anchor = max([c for c in candidates if pd.notna(c)])

    as_of_date = anchor.to_period("Q").end_time.normalize()

    # -------------------------
    # latest subscription per account
    # -------------------------
    subs_sorted = subscriptions.sort_values(["account_id", "end_date"], ascending=[True, True])
    latest_sub = subs_sorted.groupby("account_id", as_index=False).tail(1).copy()

    if "seats" not in latest_sub.columns:
        latest_sub["seats"] = np.nan
    if "arr_amount" not in latest_sub.columns:
        latest_sub["arr_amount"] = np.nan

    latest_sub["as_of_date"] = as_of_date
    latest_sub["days_to_contract_end_current"] = (latest_sub["end_date"] - latest_sub["as_of_date"]).dt.days

    base = latest_sub.merge(
        accounts[["account_id", "signup_date"]],
        on="account_id",
        how="left",
    )

    q_cur = as_of_date.to_period("Q")
    q_prev = (as_of_date - pd.offsets.QuarterEnd(1)).to_period("Q")

    # -------------------------
    # usage aggregation (optional)
    # -------------------------
    if usage is not None:
        usage = _apply_aliases(usage, DEFAULT_ALIASES)
        if "subscription_id" not in usage.columns or "usage_date" not in usage.columns:
            usage_cur = pd.Series(0, index=base.index)
            usage_prev = pd.Series(0, index=base.index)
        else:
            usage["usage_date"] = _safe_datetime(usage["usage_date"])
            if "usage_count" not in usage.columns:
                usage["usage_count"] = 1

            usage["q"] = usage["usage_date"].dt.to_period("Q")
            agg = usage.groupby(["subscription_id", "q"], as_index=False)["usage_count"].sum()

            cur_map = agg[agg["q"] == q_cur].set_index("subscription_id")["usage_count"]
            prev_map = agg[agg["q"] == q_prev].set_index("subscription_id")["usage_count"]

            usage_cur = base["subscription_id"].map(cur_map).fillna(0)
            usage_prev = base["subscription_id"].map(prev_map).fillna(0)
    else:
        usage_cur = pd.Series(0, index=base.index)
        usage_prev = pd.Series(0, index=base.index)

    # -------------------------
    # tickets aggregation + satisfaction (optional)
    # -------------------------
    if tickets is not None:
        tickets = _apply_aliases(tickets, DEFAULT_ALIASES)
        if "account_id" not in tickets.columns or "submitted_at" not in tickets.columns:
            tickets_cur = pd.Series(0, index=base.index)
            tickets_prev = pd.Series(0, index=base.index)
            avg_sat_cur = pd.Series(np.nan, index=base.index)
        else:
            tickets["submitted_at"] = _safe_datetime(tickets["submitted_at"])
            tickets["q"] = tickets["submitted_at"].dt.to_period("Q")

            tcount = (
                tickets.groupby(["account_id", "q"], as_index=False)
                .size()
                .rename(columns={"size": "tickets_opened"})
            )
            cur_map = tcount[tcount["q"] == q_cur].set_index("account_id")["tickets_opened"]
            prev_map = tcount[tcount["q"] == q_prev].set_index("account_id")["tickets_opened"]

            tickets_cur = base["account_id"].map(cur_map).fillna(0)
            tickets_prev = base["account_id"].map(prev_map).fillna(0)

            if "satisfaction_score" in tickets.columns:
                sat = tickets.dropna(subset=["satisfaction_score"]).copy()
                sat["satisfaction_score"] = pd.to_numeric(sat["satisfaction_score"], errors="coerce")
                sat = sat.dropna(subset=["satisfaction_score"])
                sat = sat[sat["q"] == q_cur]
                sat_avg = sat.groupby("account_id")["satisfaction_score"].mean()
                avg_sat_cur = base["account_id"].map(sat_avg)
            else:
                avg_sat_cur = pd.Series(np.nan, index=base.index)
    else:
        tickets_cur = pd.Series(0, index=base.index)
        tickets_prev = pd.Series(0, index=base.index)
        avg_sat_cur = pd.Series(np.nan, index=base.index)

    # seats/arr from subscription snapshot (treat as "current", use same for prev)
    seats_cur = pd.to_numeric(base["seats"], errors="coerce")
    arr_cur = pd.to_numeric(base["arr_amount"], errors="coerce")

    single = pd.DataFrame(
        {
            "account_id": base["account_id"].astype(str),
            "signup_date": base["signup_date"],
            "as_of_date": base["as_of_date"],
            "plan_tier": base["plan_tier"].astype(str),
            "usage_count_current": usage_cur,
            "usage_count_prev": usage_prev,
            "tickets_opened_current": tickets_cur,
            "tickets_opened_prev": tickets_prev,
            "days_to_contract_end_current": pd.to_numeric(base["days_to_contract_end_current"], errors="coerce"),
            "seats_current": seats_cur,
            "seats_prev": seats_cur,
            "arr_current": arr_cur,
            "arr_prev": arr_cur,
            "avg_satisfaction_current": avg_sat_cur,
        }
    )

    return build_from_single_raw_current_prev(single)
